import type { Metadata } from "next";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { AuthProvider } from "./context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        style={{display: "flex", minHeight: "100vh", flexDirection: "column", background: "linear-gradient(to bottom, #f0f8ff 0%, #f0f8ff 25%, #ffffff 100%)"}}
      >
      {/* <AuthProvider> */}
      <Header />
      <main style={{ flex: 1, marginTop: "60px" }}>
        {children}
      </main>
      <Footer />
      {/* </AuthProvider> */}
      </body>
    </html>
  );
}

